### PR TITLE
Managing API keys

### LINKED ISSUE #853: Add support for creating/re-creating api keys.
### ⚠️ Please check that this feature request hasn't been suggested before.

- [X] I searched previous [Ideas in Discussions](https://github.com/homanp/superagent/discussions/categories/ideas) didn't find any similar feature requests.
- [X] I searched previous [Issues](https://github.com/homanp/superagent/labels/enhancement) didn't find any similar feature requests.

### 🔖 Feature description

A user should be able to create new or re-create the api key.

### Acknowledgements

- [X] My issue title is concise and descriptive.
- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for the maintainers to understand and evaluate this request.

### PR DESCRIPTION
**Pull request by elisalimli**
Fixes #853

### CODE REVIEW

**Review by homanp — COMMENTED** [review]
@elisalimli would mind describing how you implement this? Hard for me to follow exactly what happens.

**Comment by elisalimli** [comment]
> @elisalimli would mind describing how you implement this? Hard for me to follow exactly what happens.

@homanp adds ability to manage API keys (JWT tokens). Previously we was offering only one API key, so people was not able to re-create or change it in any way. Now they can :)

**Review by homanp — CHANGES_REQUESTED** [review]
The UI doesn't list the first API key that is generated on signup. 
Screenshot 2024-02-28 at 14 15 58

**Comment by elisalimli** [comment]
@homanp That's a intended decision. That API key is saved in the database. And used for all the requests over all the app.

**Comment by homanp** [comment]
@elisalimli Good work on this!

**Review by homanp — APPROVED** [review]

**Pull request merged**
