### PR TITLE
Added CODE_OF_CONDUCT.md

### PR DESCRIPTION
**Pull request by Abhishekgupta204**
## Summary

Fixes

Depends on

## Test plan

-

## Checklist

- [ ] My code follows the code style of this project and passes `make format`.
- [ ] My change requires a change to the documentation.
- [ ] I have [updated the documentation](https://docs.superagent.sh/) accordingly.
- [ ] My change has adequate unit test coverage.

### CODE REVIEW

**Comment by shuriken-bytes** [comment]
This is a new file that adds the Contributor Covenant Code of Conduct to the project. It outlines the standards and behavior expected from community members and provides guidelines for enforcement. It is important to have a code of conduct in place to ensure a safe and inclusive environment for all contributors. Thank you, @Abhishekgupta204, for adding this! 👍🏼

**Comment by Abhishekgupta204** [comment]
@homanp I have added the code of conduct file to make it easier for other people on how can they contribute to this repository.
Please review my pull request and merge it.

**Comment by mohitd404** [comment]
> @homanp I have added the code of conduct file to make it easier for other people on how can they contribute to this repository. Please review my pull request and merge it.

Code of conduct is already there under Lisence file KIndly check !

**Comment by homanp** [comment]
@Abhishekgupta204 we already have a code of conduct in this repo.

**Pull request closed without merging**
