### PR TITLE
Add psychic integration

### PR DESCRIPTION
**Pull request by jasonwcfan**
## Summary

Add psychic as a source of documents for superagent's backend.

Fixes
- N/a

Depends on
- no new dependencies

## Test plan
- will test locally before merging in

-

## Screenshots
CleanShot 2023-05-31 at 20 17 35@2x

## Checklist

- [x] My code follows the code style of this project and passes {`style_guide_run_command`}.
- [ ] My change requires a change to the documentation.
- [ ] I have [updated the documentation](https://docs.superagent.sh/) accordingly.
- [ ] My change has adequate [Unit Test coverage]({TestCoverage}).

### CODE REVIEW

**Comment by jasonwcfan** [comment]
Not ready to merge yet - has a dependency on a PR to langchain that still needs to go in

**Comment by homanp** [comment]
> Not ready to merge yet - has a dependency on a PR to langchain that still needs to go in

Thank you for this @jasonwcfan

**Comment by homanp** [comment]
@jasonwcfan I'm releasing a refactoring of how we do ingestion and agent creation with superagent. As soon as it's merged I will do some refactoring of you PR as well to fit the new specs.

Also, ping me when your PR is merged by LangChain.

**Comment by jasonwcfan** [comment]
@homanp will do! Planning on making the langchain updates this weekend.

**Comment by yusofy** [comment]
@jasonwcfan was looking at the langchain document loader for psychic - do you plan on adding the ability for users to point to a self hosted version of psychic?

**Comment by jasonwcfan** [comment]
Re-added back psychic, ready for review now @homanp !

**Comment by jasonwcfan** [comment]
hey @yusofy sorry it's been awhile, my github notifications weren't working properly.

Yes, we plan on making that possible soon! Are you self hosting Psychic or do you plan to do so?

**Comment by yusofy** [comment]
hey @jasonwcfan  I was looking at your PR and it peeked my interest. I need to look more into psychic because I have a specific way of doing things right now. If I were go with psychic, I would self host. 
Also - I have a slight comment about the PR, I think the name should be something other than API. Technically a lot of things can use API that psychic may not have at this point. If I had to make a suggestion, I would call it psychic. That way people know what it is. I think there are more benefits than drawbacks in changing it.

**Comment by jasonwcfan** [comment]
@yusofy Got it - I'm kind of curious how you do things right now. We're working on an open source document transformation library that basically extends Psychic from being extract only to extract + transform for data pulled from various APIs, would love to get your feedback on it: https://github.com/psychic-api/doctran

Also re: naming, my thinking was that API is more descriptive than "Psychic", but you're right that it can also mean many things. Renamed API to Psychic but I'll defer to @homanp on what he wants to call it in the codebase.

**Comment by homanp** [comment]
@jasonwcfan I pulled this into #143 and did some changes + added a UI
Screenshot 2023-07-03 at 00 47 24

Closing this in favour for #143

**Pull request closed without merging**
