### PR TITLE
Add Provider field to Agent fixes Azure Openai

### PR DESCRIPTION
**Pull request by f1delius**
## Summary

Adds llm provider while creating agent .
Fixes azure openai issue.

Fixes

Depends on

## Test plan

-

## Checklist

- [x] My code follows the code style of this project and passes `make format`.
- [ ] My change requires a change to the documentation.
- [ ] I have [updated the documentation](https://docs.superagent.sh/) accordingly.
- [ ] My change has adequate unit test coverage.

### CODE REVIEW

**Comment by homanp** [comment]
@f1delius could you explain how this fixes the Azure issue? Is it problem with the provider mapping?

**Comment by f1delius** [comment]
https://github.com/homanp/superagent/blob/6f91f868670c6f5a62e7e8fdedd7543fb2a85b10/libs/superagent/app/utils/llm.py#L10-L19

At present,it iterates over LLM_MAPPING to find provider based on llmModel but you can't specify model name for azure.If we provide provider in the api call,it won't iterate over the mapping and set it directly.


The only issue in this approach would be if someone missspels llmModel while using api,but they can fix it by updating the agent.

https://github.com/homanp/superagent/blob/6f91f868670c6f5a62e7e8fdedd7543fb2a85b10/libs/superagent/app/api/agents.py#L80-L87

And on ui,everytime you create agent it sets llmModel to default value.
https://github.com/homanp/superagent/blob/6f91f868670c6f5a62e7e8fdedd7543fb2a85b10/libs/ui/config/site.ts#L92

**Comment by homanp** [comment]
@f1delius got it. thanks for this!

**Comment by elisalimli** [comment]
This is fixed by #684.

**Pull request closed without merging**
