### PR TITLE
Adding support for OSS LLMs

### PR DESCRIPTION
**Pull request by elisalimli**
## Summary

- [x] Added support for Hugging face models
- [x] Migrate to Langfuse v2
- [x] Fix Workflows

## Test Plan

- Make sure to run `poetry install` command in your `libs/superagent` folder since I updated langfuse version to latest one

## Checklist

- [x] My code follows the code style of this project and passes `make format`.
- [x] My change requires a change to the documentation.
- [ ] I have [updated the documentation](https://docs.superagent.sh/) accordingly.
- [ ] My change has adequate unit test coverage.

### CODE REVIEW

**Comment by elisalimli** [comment]
@homanp please have a look at ReAct agent prompt. Let's see how we can make it better.

https://github.com/homanp/superagent/blob/add-huggingface-llms/libs/superagent/app/agents/react_agent.py#L59-L76

**Review by homanp — CHANGES_REQUESTED** [review]
Getting this error when running the Agent without tools: 

```
  File "/Users/ismailpelaseyed/Projects/superagent/libs/superagent/app/api/agents.py", line 216, in invoke
    trace = langfuse.trace(
            ^^^^^^^^^^^^^^^
TypeError: Langfuse.trace() got an unexpected keyword argument 'id'
```

**Comment by elisalimli** [comment]
> Getting this error when running the Agent without tools:
> 
> ```
>   File "/Users/ismailpelaseyed/Projects/superagent/libs/superagent/app/api/agents.py", line 216, in invoke
>     trace = langfuse.trace(
>             ^^^^^^^^^^^^^^^
> TypeError: Langfuse.trace() got an unexpected keyword argument 'id'
> ```

have you run `poetry install` command in the `libs/superagent` folder?

**Review by homanp — CHANGES_REQUESTED** [review]
@elisalimli getting the following error when testing the agent with a browser tool: 
```
> Entering new AgentExecutor chain...
Summarizing a website requires visiting the website and extracting the most important information. In this case, the website is "Superagent.sh". I can use the browser tool to visit the website and gather the necessary information.

Action: browser

Action Input: Superagent.sh

ObservationERROR:  1 validation error for UpdateSpanBody
statusMessage
  str type expected (type=type_error.str)
Traceback (most recent call last):
  File "/Users/ismailpelaseyed/Projects/superagent/.venv/lib/python3.11/site-packages/langfuse/client.py", line 1149, in update
    request = UpdateSpanBody(**span_body)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for UpdateSpanBody
statusMessage
  str type expected (type=type_error.str)
ERROR:  Error in send_message: Superagent.shObservation
```
Datasources work as expected.

**Comment by elisalimli** [comment]
Fixed by #814

**Pull request closed without merging**
