### PR TITLE
Feature: Add reusable data-table-pagination.tsx component (#583)

### LINKED ISSUE #583: Add pagination to `Agens` and `Worflows` list views
### ⚠️ Please check that this feature request hasn't been suggested before.

- [X] I searched previous [Ideas in Discussions](https://github.com/homanp/superagent/discussions/categories/ideas) didn't find any similar feature requests.
- [X] I searched previous [Issues](https://github.com/homanp/superagent/labels/enhancement) didn't find any similar feature requests.

### 🔖 Feature description

We should add pagination to the `Agents` and `Workflows` list pages.

### 📝 Additional Context

_No response_

### Acknowledgements

- [X] My issue title is concise and descriptive.
- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for the maintainers to understand and evaluate this request.

### PR DESCRIPTION
**Pull request by RutamBhagat**
## Summary

Adds pagination to Agents and Workflows list views 

Fixes #583

Depends on

## Test plan

-

## Screenshots

https://github.com/homanp/superagent/assets/72187009/e9703190-fe10-41ad-a331-d6de6724154b

## Checklist

- [x] My code follows the code style of this project and passes `make format`.
- [ ] My change requires a change to the documentation.
- [ ] I have [updated the documentation](https://docs.superagent.sh/) accordingly.
- [ ] My change has adequate unit test coverage.

### CODE REVIEW

**Comment by shuriken-bytes** [comment]
Reviewing pull request by @RutamBhagat.

Overall, the changes look good. The addition of the `DataTablePagination` component will provide pagination functionality to the data tables in the `agents` and `workflows` modules.

There are no major issues or concerns with the code changes.

Great job, @RutamBhagat! 👍🎉

**Comment by elisalimli** [comment]
Great job, please add pagination for the fetching part. We don't need to fetch all the agents/workflows if a user is not viewing them.

**Comment by homanp** [comment]
Thanks @RutamBhagat will test and merge!

**Review by homanp — CHANGES_REQUESTED** [review]
@RutamBhagat would you mind adding pagination to the APi request as well?!

**Comment by homanp** [comment]
> @RutamBhagat would you mind adding pagination to the APi request as well?!

@elisalimli perhaps you could take a look at adding pagination the the request itself?

**Comment by elisalimli** [comment]
Done. #610

**Pull request closed without merging**
