### PR TITLE
Adding Pagintion for workflows and agents page

### LINKED ISSUE #583: Add pagination to `Agens` and `Worflows` list views
### ⚠️ Please check that this feature request hasn't been suggested before.

- [X] I searched previous [Ideas in Discussions](https://github.com/homanp/superagent/discussions/categories/ideas) didn't find any similar feature requests.
- [X] I searched previous [Issues](https://github.com/homanp/superagent/labels/enhancement) didn't find any similar feature requests.

### 🔖 Feature description

We should add pagination to the `Agents` and `Workflows` list pages.

### 📝 Additional Context

_No response_

### Acknowledgements

- [X] My issue title is concise and descriptive.
- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for the maintainers to understand and evaluate this request.

### PR DESCRIPTION
**Pull request by elisalimli**
## Summary

This PR fixes #583
 
- [x] My code follows the code style of this project and passes `make format`.
- [ ] My change requires a change to the documentation.
- [ ] I have [updated the documentation](https://docs.superagent.sh/) accordingly.
- [ ] My change has adequate unit test coverage.

### CODE REVIEW

**Comment by shuriken-bytes** [comment]
The changes in this pull request include:
- Updating the `list` functions in `agents.py` and `workflows.py` to include pagination functionality.
- Adding a `total_pages` field to the response models `AgentList` and `WorkflowList` in `response.py`.
- Adding a new component `DataTablePagination` to handle pagination in the UI.
- Updating the `Agents` and `Workflows` pages to include pagination functionality.

Overall, the changes look good and provide a way to paginate through the list of agents and workflows. The code is well-structured and follows the existing conventions. Nice work, @elisalimli! 👍

One suggestion I have is to add some error handling in case there is an exception while fetching the agents or workflows. It would be helpful to display an error message to the user if something goes wrong.

**Comment by elisalimli** [comment]
@RutamBhagat please resolve merge conflicts.

**Comment by RutamBhagat** [comment]
> @RutamBhagat please resolve merge conflicts.

Um, I am sorry but I do not know how to do that

**Review by homanp — APPROVED** [review]
Looks good.

**Pull request merged**
