### PR TITLE
Workflow settings

### PR DESCRIPTION
**Pull request by elisalimli**
## Summary

This PR adds workflow settings page

### CODE REVIEW

**Comment by shuriken-bytes** [comment]
Thank you for the pull request, @elisalimli! Here's my review:

- In `libs/ui/app/agents/[agentId]/chat.tsx`, the addition of the `key` prop in the `Message` component is necessary to avoid rendering issues when the `messages` array changes. Good job!
- In `libs/ui/app/workflows/[workflowId]/chat.tsx`, the removal of the `console.log` statement is appropriate. It's always a good practice to remove debugging statements before committing the code.
- In `libs/ui/app/workflows/[workflowId]/settings/danger-zone.tsx`, the code looks good. It adds a new component for the "Danger Zone" section, which allows users to delete a workflow. Well done!
- In `libs/ui/app/workflows/[workflowId]/settings/page.tsx`, the code looks good. It adds a new page component for the workflow settings, which includes the "Update" and "Danger Zone" components. Great work!
- In `libs/ui/app/workflows/[workflowId]/settings/update.tsx`, the code looks good. It adds a new component for updating the workflow settings. Nice job!
- In `libs/ui/app/workflows/[workflowId]/workflow-editor.tsx`, the addition of the link to the workflow settings page is a good enhancement. It allows users to easily navigate to the settings page. Well done!
- In `libs/ui/components/ui/alert-dialog.tsx`, the addition of the `@radix-ui/react-alert-dialog` package is necessary for the new "Danger Zone" component. Good job!
- In `libs/ui/lib/api.ts`, the addition of the `patchWorkflow` and `deleteWorkflow` methods is necessary for updating and deleting workflows. Well done!
- In `libs/ui/package-lock.json` and `libs/ui/package.json`, the addition of the `@radix-ui/react-alert-dialog` package is necessary for the new "Danger Zone" component. Good job!

Overall, great work on the pull request, @elisalimli! I appreciate the effort you put into adding new functionality and improving the codebase. Keep up the good work! 👏🎉

**Comment by homanp** [comment]
@elisalimli this branch has conflicts, please resolve them so that I can review/merge.

**Review by homanp — CHANGES_REQUESTED** [review]
@elisalimli please fix merge conflicts so I can review.

**Review by homanp — CHANGES_REQUESTED** [review]
@elisalimli overall these changes look good. One request I have is to put the ui elements you have in /settings inside a modal in the `/workflow/id`. This way the user doesn't have to get redirected to a new page and the UI.

**Review by homanp — APPROVED** [review]

**Comment by homanp** [comment]
@elisalimli good work! Merged, will record a demo tomorrow.

**Pull request merged**
