### PR TITLE
Fix `Digitalocean` deployment config

### LINKED ISSUE #41: Digital ocean button deploy not work
The display button in digital ocean does not work.

An error is thrown when it is observed that the example file does not exist.

### PR DESCRIPTION
**Pull request by homanp**
## Summary

Fixes an issue `Digitalocean` deployment config

Fixes #41

### CODE REVIEW

**Comment by ferlinuxgit** [comment]
i get the following error trying to use it:

2023-05-19T09:49:44.511591610Z [34m╭────────────[34m[30m[44m git repo clone [0m[0m[34m───────────╼[0m
2023-05-19T09:49:44.511633143Z [34m│[0m [34m › fetching app source code[0m
2023-05-19T09:49:44.511637436Z [34m│[0m => Selecting branch "main"
2023-05-19T09:49:44.511640495Z [34m│[0m => Checking out commit "ccf5e98784fba5262ad0d3ec7831835d3f7823df"
2023-05-19T09:49:44.511647566Z [34m│[0m 
2023-05-19T09:49:44.511655027Z [34m│[0m [32m ✔ cloned repo to [35m/workspace[0m[0m
2023-05-19T09:49:44.511658183Z [34m╰────────────────────────────────────────╼[0m
2023-05-19T09:49:44.511660540Z 
2023-05-19T09:49:44.511663014Z [34m╭────────────[34m[30m[44m buildpack detection [0m[0m[34m───────────╼[0m
2023-05-19T09:49:44.511665288Z [34m│[0m [34m › using Ubuntu 18.04 stack[0m
2023-05-19T09:49:45.422130144Z [34m│[0m [31m ✘ could not detect app files that match known buildpacks.[0m
2023-05-19T09:49:45.422182770Z [34m│[0m [31m   please ensure that the files required by the desired language's buildpack exist in the repo.[0m
2023-05-19T09:49:45.422995101Z [34m│[0m [31m   review the buildpack documentation for more info: [1mhttps://do.co/apps-buildpacks[0m[0m

**Comment by homanp** [comment]
> i get the following error trying to use it:
> 
> 2023-05-19T09:49:44.511591610Z �[34m╭────────────�[34m�[30m�[44m git repo clone �[0m�[0m�[34m───────────╼�[0m 2023-05-19T09:49:44.511633143Z �[34m│�[0m �[34m › fetching app source code�[0m 2023-05-19T09:49:44.511637436Z �[34m│�[0m => Selecting branch "main" 2023-05-19T09:49:44.511640495Z �[34m│�[0m => Checking out commit "ccf5e98784fba5262ad0d3ec7831835d3f7823df" 2023-05-19T09:49:44.511647566Z �[34m│�[0m 2023-05-19T09:49:44.511655027Z �[34m│�[0m �[32m ✔ cloned repo to �[35m/workspace�[0m�[0m 2023-05-19T09:49:44.511658183Z �[34m╰────────────────────────────────────────╼�[0m 2023-05-19T09:49:44.511660540Z 2023-05-19T09:49:44.511663014Z �[34m╭────────────�[34m�[30m�[44m buildpack detection �[0m�[0m�[34m───────────╼�[0m 2023-05-19T09:49:44.511665288Z �[34m│�[0m �[34m › using Ubuntu 18.04 stack�[0m 2023-05-19T09:49:45.422130144Z �[34m│�[0m �[31m ✘ could not detect app files that match known buildpacks.�[0m 2023-05-19T09:49:45.422182770Z �[34m│�[0m �[31m please ensure that the files required by the desired language's buildpack exist in the repo.�[0m 2023-05-19T09:49:45.422995101Z �[34m│�[0m �[31m review the buildpack documentation for more info: �[1mhttps://do.co/apps-buildpacks�[0m�[0m

hmmm, will look into it.

**Comment by ferlinuxgit** [comment]
Is there any additional configuration to do in digital ocean?

**Comment by ferlinuxgit** [comment]
image
I've tried anyway and always get the same error.

**Comment by homanp** [comment]
> image
> 
> I've tried anyway and always get the same error.

Will resolve today

**Pull request merged**
