### PR TITLE
Add possiblity to return structured data

### LINKED ISSUE #455: Structured output
### ⚠️ Please check that this feature request hasn't been suggested before.

- [X] I searched previous [Ideas in Discussions](https://github.com/homanp/superagent/discussions/categories/ideas) didn't find any similar feature requests.
- [X] I searched previous [Issues](https://github.com/homanp/superagent/labels/enhancement) didn't find any similar feature requests.

### 🔖 Feature description

A user should be able to pass in a structure input schema to define output achema

### 📝 Additional Context

_No response_

### Acknowledgements

- [X] My issue title is concise and descriptive.
- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for the maintainers to understand and evaluate this request.

### PR DESCRIPTION
**Pull request by homanp**
## Summary

Fixes #455 

## Checklist

- [x] My code follows the code style of this project and passes `make format`.
- [ ] My change requires a change to the documentation.
- [ ] I have [updated the documentation](https://docs.superagent.sh/) accordingly.
- [ ] My change has adequate unit test coverage.

### CODE REVIEW

**Comment by shuriken-bytes** [comment]
Reviewing pull request by @homanp

Overall, the changes look good. It seems like the author added a new `output_schema` parameter to the `AgentBase` class and made some modifications to the `_get_prompt` method in the `AgentBase` class and the `send_message` function in the `agents.py` file.

Here are my comments:

1. In the `AgentBase` class:
   - The `output_schema` parameter was added to the `__init__` method. This allows the user to pass an output schema when creating an instance of `AgentBase`.
   - In the `_get_prompt` method, the author added logic to include the output schema in the prompt message if it is provided. This is a good addition as it provides more context to the user about the expected output format.

2. In the `agents.py` file:
   - The `output_schema` parameter was added to the `send_message` function. This allows the user to pass an output schema when invoking an agent.
   - If an output schema is provided, the author added logic to parse the output as JSON and return it as part of the response. This is a good addition as it ensures that the output is in the expected format.

No major issues or concerns with the changes. Good job, @homanp! 👍🏼

**Comment by trotsky1997** [comment]
dude, llm would torture you with its bad json output...

**Comment by homanp** [comment]
> dude, llm would torture you with its bad json output... 

Yeah, this is a quick fix. Investigating other approaches to accomplish this. Any ideas? Played around with jsonformer but that only works on non-gpt llms.

**Comment by homanp** [comment]
> dude, llm would torture you with its bad json output...

Any contributions here would be very welcome 🙏

**Comment by trotsky1997** [comment]
> > dude, llm would torture you with its bad json output...
> 
> Yeah, this is a quick fix. Investigating other approaches to accomplish this. Any ideas? Played around with jsonformer but that only works on non-gpt llms.

:( I have been tortured by dummy llms, may be you can check this reddit page
https://www.reddit.com/r/MachineLearning/comments/16j1e9j/comment/k12czcw/?context=3

**Pull request merged**
