### PR TITLE
local setup for running dev

### PR DESCRIPTION
**Pull request by dantheman0207**
## Summary

Would like to simplify local setup for running dev. Added docker-compose and changed some small defaults for consistency. The idea is to be able to start a local dev setup that is complete including db with a single command.

It is working, but I would like to add a script to seed the db with a test user and possibly other test data.

Fixes

Depends on

## Test plan

-

## Checklist

- [ ] My code follows the code style of this project and passes `make format`.
- [ ] My change requires a change to the documentation.
- [ ] I have [updated the documentation](https://docs.superagent.sh/) accordingly.
- [ ] My change has adequate unit test coverage.

### CODE REVIEW

**Comment by dantheman0207** [comment]
I'm having a little trouble with the db. Would love some help writing a script to seed test data into the db. Run it when starting up the db. Is this something already written with prisma and I missed it? 

I was thinking of having a test user, a test agent, and perhaps a test document that are already created in the db when you start it up.

**Comment by homanp** [comment]
> I'm having a little trouble with the db. Would love some help writing a script to seed test data into the db. Run it when starting up the db. Is this something already written with prisma and I missed it? 
> 
> 
> 
> I was thinking of having a test user, a test agent, and perhaps a test document that are already created in the db when you start it up.

Sounds like a good idea, we don't have any seed data at this point.

**Comment by homanp** [comment]
> @homanp How do you test locally? I assume you have a persistent Postgres set up for local testing. What do you use for auth or creating users when testing backend functionality locally?

I just run another Supabase db . You really only need to put the connection string to the env variables. DATABASE_URL and DATABASE_MIGRATION_URL (non pooling connection string to db)

**Comment by dantheman0207** [comment]
What is the difference between DATABASE_URL and DATABASE_MIGRATION_URL?

I set up supabase and pinecone and I am running it locally on the main branch off of the base repository (yours) but when I try to create a standard websearch tool it fails. I think I have everything set up the same way, nothing changed, but it is strange. This is starting from an empty database with no data and applying all the migrations. I've wiped it and restarted several times and always get the same result.

**Comment by homanp** [comment]
> What is the difference between DATABASE_URL and DATABASE_MIGRATION_URL?
> 
> 
> 
> I set up supabase and pinecone and I am running it locally on the main branch off of the base repository (yours) but when I try to create a standard websearch tool it fails. I think I have everything set up the same way, nothing changed, but it is strange. This is starting from an empty database with no data and applying all the migrations. I've wiped it and restarted several times and always get the same result.

Did you det up the bling search API in the `.env`? If you are going to run tools locally you need to fill all the `.env` variables for those.

**Comment by dantheman0207** [comment]
> > What is the difference between DATABASE_URL and DATABASE_MIGRATION_URL?
> > I set up supabase and pinecone and I am running it locally on the main branch off of the base repository (yours) but when I try to create a standard websearch tool it fails. I think I have everything set up the same way, nothing changed, but it is strange. This is starting from an empty database with no data and applying all the migrations. I've wiped it and restarted several times and always get the same result.
> 
> Did you det up the bling search API in the `.env`? If you are going to run tools locally you need to fill all the `.env` variables for those.

Ok, makes sense. What if I just want to create an agent and use it as a tool for another agent? I just want to test my setup because I am as of now unable to just create an agent using OpenAI, I gave it a working API key. UI just hangs and backend gives a HTTP 500.

Also is there some way to increase the log level? I was expecting some specific error to show up but I am just getting HTTP 500's for this stuff.

**Comment by homanp** [comment]
> > > What is the difference between DATABASE_URL and DATABASE_MIGRATION_URL?
> 
> > > I set up supabase and pinecone and I am running it locally on the main branch off of the base repository (yours) but when I try to create a standard websearch tool it fails. I think I have everything set up the same way, nothing changed, but it is strange. This is starting from an empty database with no data and applying all the migrations. I've wiped it and restarted several times and always get the same result.
> 
> > 
> 
> > Did you det up the bling search API in the `.env`? If you are going to run tools locally you need to fill all the `.env` variables for those.
> 
> 
> 
> Ok, makes sense. What if I just want to create an agent and use it as a tool for another agent? I just want to test my setup because I am as of now unable to just create an agent using OpenAI, I gave it a working API key. UI just hangs and backend gives a HTTP 500.
> 
> 
> 
> Also is there some way to increase the log level? I was expecting some specific error to show up but I am just getting HTTP 500's for this stuff.

1. Create an Agent. 
2. Then Create a Tool and select the agent you created.
3. Create a new agent and choose the tool you created. 

I'll record a tutorial on this today and post.

**Comment by dantheman0207** [comment]
Fresh install, reset the db before and applied all migrations, based on `main` from your repo. I try to create an OpenAI agent, no tools, no documents, default prompt, and get this error:


I have all the mandatory env vars set and I don't know what else could cause this.

I appreciate your help! Always the hardest part with open source is getting everything set up locally.

**Comment by dantheman0207** [comment]
> Fresh install, reset the db before and applied all migrations, based on `main` from your repo. I try to create an OpenAI agent, no tools, no documents, default prompt, and get this error: Screenshot 2023-07-26 at 20 44 38
> 
> I have all the mandatory env vars set and I don't know what else could cause this.
> 
> I appreciate your help! Always the hardest part with open source is getting everything set up locally.

Found the issue. If there are no agents or documents it returns a HTTP 500, even though no documents is actually the correct return value from the database.

**Comment by homanp** [comment]
Ok ok, file a bug

https://twitter.com/pelaseyed
https://github.com/homanp

________________________________

**Review by homanp — CHANGES_REQUESTED** [review]
@dantheman0207 Looks good. Please update the README with how to run this and other necessary changes.

**Comment by dantheman0207** [comment]
I'm going to abandon this PR for now as I have everything working with supabase. I was hoping to use a generic Postgres and docker compose, or maybe a local copy of supabase to run against so I could dump data into the db directly for testing, but seems like overkill now I have everything working. Maybe I will revisit later.

**Comment by homanp** [comment]
> I'm going to abandon this PR for now as I have everything working with supabase. I was hoping to use a generic Postgres and docker compose, or maybe a local copy of supabase to run against so I could dump data into the db directly for testing, but seems like overkill now I have everything working. Maybe I will revisit later.

Closing this then.

**Pull request closed without merging**
