### PR TITLE
New Datasource Schema in SAML

### LINKED ISSUE #785: Add `name` key to `data` node in SAML
### ⚠️ Please check that this feature request hasn't been suggested before.

- [X] I searched previous [Ideas in Discussions](https://github.com/homanp/superagent/discussions/categories/ideas) didn't find any similar feature requests.
- [X] I searched previous [Issues](https://github.com/homanp/superagent/labels/enhancement) didn't find any similar feature requests.

### 🔖 Feature description

```yaml
data: 
  - index:
      urls:
        - <url>
        - <url>
      name:
      use_for:
```

This will also support the super-rag implementation.. 

### 📝 Additional Context

_No response_

### Acknowledgements

- [X] My issue title is concise and descriptive.
- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for the maintainers to understand and evaluate this request.

### PR DESCRIPTION
**Pull request by elisalimli**
## Warning
*This is a breaking change, we need to migrate existing data*

## Tasks:
- [ ] update example SAMLs to conform new schema

## Summary

This PR changes SAML schema for datasources.  (this changes is needed for to support superrag).

Here's an example of new database schema:

```yaml
workflows:
  - superagent:
      llm: gpt-4-1106-preview
      data:
        earnings:
          urls:
            - https://s2.q4cdn.com/299287126/files/doc_financials/2023/q3/AMZN-Q3-2023-Earnings-Release.pdf
          use_for: Answering questions about earning report
      name: Earnings assistant
      intro: 👋 Hi there! How can I help you?
      prompt: Use the earnings report to answer any questions
```

Fixes #785

### CODE REVIEW

**Review by homanp — CHANGES_REQUESTED** [review]
Overall looks good. But I don't think the schema design should look like that. Having the name as the key of the index is a bit weird and people won't understand it. 

Better to have something like this:

```
data:
        index:
          name: earnings reports
          urls:
            - https://s2.q4cdn.com/299287126/files/doc_financials/2023/q3/AMZN-Q3-2023-Earnings-Release.pdf
          use_for: Answering questions about earning report
      name: Earnings assistant
      intro: 👋 Hi there! How can I help you?
      prompt: Use the earnings report to answer any questions
```

**Comment by homanp** [comment]
This only breaks new agents? Why would need to migrate?

**Comment by elisalimli** [comment]
> Overall looks good. But I don't think the schema design should look like that. Having the name as the key of the index is a bit weird and people won't understand it.
> 
> Better to have something like this:
> 
> ```
> data:
>         index:
>           name: earnings reports
>           urls:
>             - https://s2.q4cdn.com/299287126/files/doc_financials/2023/q3/AMZN-Q3-2023-Earnings-Release.pdf
>           use_for: Answering questions about earning report
>       name: Earnings assistant
>       intro: 👋 Hi there! How can I help you?
>       prompt: Use the earnings report to answer any questions
> ```

then the "index" in your example does not have any meaning in the processing process, correct?

**Comment by homanp** [comment]
> > Overall looks good. But I don't think the schema design should look like that. Having the name as the key of the index is a bit weird and people won't understand it.
> > Better to have something like this:
> > ```
> > data:
> >         index:
> >           name: earnings reports
> >           urls:
> >             - https://s2.q4cdn.com/299287126/files/doc_financials/2023/q3/AMZN-Q3-2023-Earnings-Release.pdf
> >           use_for: Answering questions about earning report
> >       name: Earnings assistant
> >       intro: 👋 Hi there! How can I help you?
> >       prompt: Use the earnings report to answer any questions
> > ```
> 
> then the "index" in your example does not have any meaning in the processing process, correct?

No it's just a node. And you might want multiple indexes later. Then it can be transformed into a list.

**Pull request closed without merging**
