### PR TITLE
Integrate E2B code execution tool

### PR DESCRIPTION
**Pull request by jakubno**
## Summary

This PR adds a e2b as a code executor, you will need to change the prompts little bit. It doesn't print the result at the moment, meaning the code executor doesn't return anything.

## Test plan

- Create an agent with E2B as an API tool.
- Ask the agent anything which requires to run any code

## Screenshots
image

```
Invoking: `e2b` with `{'python_code': 'def fibonacci(n):\n    fib = [3, 3]\n    for i in range(2, n):\n        fib.append(fib[i-1] + fib[i-2])\n    return fib[n-1]\n\nfibonacci(13)'}`
```

```python
def fibonacci(n):
    fib = [3, 3]
        for i in range(2, n):
                fib.append(fib[i-1] + fib[i-2])
                    return fib[n-1]
                    
fibonacci(13)  # <-- There's the problem with not printing the output
```

## Checklist

- [x] My code follows the code style of this project and passes `make format`.
- [x] My change requires a change to the documentation.
- [ ] I have [updated the documentation](https://docs.superagent.sh/) accordingly.
- [ ] My change has adequate unit test coverage.

### CODE REVIEW

**Comment by shuriken-bytes** [comment]
@jakubno Thank you for the pull request! Overall, the changes look good. I have a few suggestions:

1. In the `.env.example` file, please update the comment for the `E2B_API_KEY` variable to reflect that it is used for the E2B (code execution) tool.

2. In the `base.py` file, please reorder the imports so that `AzureChatOpenAI` is imported before `ChatOpenAI`.

3. In the `agents.py` file, please remove the unused import statement for `json`.

4. In the `llms.py` file, please reorder the imports so that `analytics` is imported before `json`.

5. In the `tools.py` file, please update the class name from `CodeExecutorInput` to `E2BCodeExecutorInput`.

6. In the `__init__.py` file, please update the class name from `CodeExecutor` to `E2BCodeExecutor`.

7. In the `pyproject.toml` file, please update the `e2b` dependency to version `^0.6.0`.

Once these changes are made, the pull request will be good to merge. Thank you again for your contribution! 👍🏼

**Comment by homanp** [comment]
@jakubno thank u for this!!

**Comment by jakubno** [comment]
You are welcome! I'll prepare better environment with preinstalled packages as discussed with @mlejva, this is just kickoff and we can fast iterate on it :)

Let me know if I can help you with anything else

**Comment by homanp** [comment]
> You are welcome! I'll prepare better environment with preinstalled packages as discussed with @mlejva, this is just kickoff and we can fast iterate on it :)
> 
> 
> 
> Let me know if I can help you with anything else

Will merge in today

**Comment by mlejva** [comment]
> > You are welcome! I'll prepare better environment with preinstalled packages as discussed with @mlejva, this is just kickoff and we can fast iterate on it :)
> > Let me know if I can help you with anything else
> 
> Will merge in today

Awesome! This is a really simple code executor/interpreter. We're happy to explore more complicated use cases though - installing deps on demand, data analysis agents (might be also suitable for https://github.com/homanp/nagato), running nextjs apps in dev mode for hot reloading for coding agents, executing shell commands (can be used for fun things like building a `ffmpeg` agent, headless browsers for browsing agents. Let us know!

**Comment by homanp** [comment]
> > > You are welcome! I'll prepare better environment with preinstalled packages as discussed with @mlejva, this is just kickoff and we can fast iterate on it :)
> 
> > > Let me know if I can help you with anything else
> 
> > 
> 
> > Will merge in today
> 
> 
> 
> Awesome! This is a really simple code executor/interpreter. We'd love to explore more complicated use cases if you're interested - installing deps on demand, data analysis agents (might be also suitable for https://github.com/homanp/nagato), running nextjs apps in dev mode for hot reloading for coding agents, executing shell commands (can be used for fun things like building a `ffmpeg` agent), headless browsers for browsing agents. Let us know :)

This is so amazing. Deps on demand most lead to latency? How do you guys handle that? Any experience to share?

**Review by homanp — APPROVED** [review]

**Comment by jakubno** [comment]
Right now, the module just runs the code, if you're missing some dependency, it'll fail. We could switch to long running playgrounds, which would allow us to install dependencies during runtime, but it would complicate the things little bit (you need to pair the conversation to the playground, ... ).

For your use-case I believe it makes sense to prepare environment with preinstalled libraries. If you know beforehand what dependencies you will need (or at least most of the time), we can install those. If you don't know, you can have preinstalled top ~100 libraries or something similar, which should help with latency.

**Comment by homanp** [comment]
> Right now, the module just runs the code, if you're missing some dependency, it'll fail. We could switch to long running playgrounds, which would allow us to install dependencies during runtime, but it would complicate the things little bit (you need to pair the conversation to the playground, ... ).
> 
> 
> 
> For your use-case I believe it makes sense to prepare environment with preinstalled libraries. If you know beforehand what dependencies you will need (or at least most of the time), we can install these. If you don't know, you can have preinstalled top ~100 libraries or something similar, which should help with latency.

Hey, I sent the dependencies to @mlejva. Are those installed? Would be good to have prior to announcing release. Is that possible?

**Pull request merged**
