### PR TITLE
Add Agent that can run OSS LLMs

### LINKED ISSUE #493: Add OSS option to LLMS.
### ⚠️ Please check that this feature request hasn't been suggested before.

- [X] I searched previous [Ideas in Discussions](https://github.com/homanp/superagent/discussions/categories/ideas) didn't find any similar feature requests.
- [X] I searched previous [Issues](https://github.com/homanp/superagent/labels/enhancement) didn't find any similar feature requests.

### 🔖 Feature description

OSS LLMs should not have access to tools if the underlying model doesn't support function calling.  So OSS LLMs can do Rag and Completion.

This could probably be done with LangChain or LlamaIndex. 

### 📝 Additional Context

_No response_

### Acknowledgements

- [X] My issue title is concise and descriptive.
- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for the maintainers to understand and evaluate this request.

### PR DESCRIPTION
**Pull request by homanp**
## Summary

This PR adds support for running Agents with Open Source LLMs. Utilizes a function-calling approach. 

Fixes #493 #388 

## Checklist

- [x] My code follows the code style of this project and passes `make format`.
- [x] My change requires a change to the documentation.
- [x] I have [updated the documentation](https://docs.superagent.sh/) accordingly.
- [ ] My change has adequate unit test coverage.

### CODE REVIEW

**Comment by shuriken-bytes** [comment]
@homanp Thank you for the pull request! I have reviewed the code and left some comments for you to address. Please take a look and make the necessary changes.

**Comment by bdqfork** [comment]
Any update? I plan to test it out soon.

**Comment by homanp** [comment]
> Any update? I plan to test it out soon.

Working on it, hoping to release the coming week

**Comment by bdqfork** [comment]
> > Any update? I plan to test it out soon.
> 
> Working on it, hoping to release the coming week

I trained a model based on mistral 7B with function calling data. I will test it when merged.

**Comment by homanp** [comment]
> > > Any update? I plan to test it out soon.
> 
> > 
> 
> > Working on it, hoping to release the coming week
> 
> 
> 
> I trained a model based on mistral 7B with function calling data. I will test it when merged.

Anything you could share?

**Comment by bdqfork** [comment]
> > > > Any update? I plan to test it out soon.
> > 
> > 
> > > 
> > 
> > 
> > > Working on it, hoping to release the coming week
> > 
> > 
> > I trained a model based on mistral 7B with function calling data. I will test it when merged.
> 
> Anything you could share?

I'm trying upload model to huggeface, maybe it can help you for test ?

**Comment by bdqfork** [comment]
> > > > Any update? I plan to test it out soon.
> > 
> > 
> > > 
> > 
> > 
> > > Working on it, hoping to release the coming week
> > 
> > 
> > I trained a model based on mistral 7B with function calling data. I will test it when merged.
> 
> Anything you could share?

I uploaded to https://huggingface.co/jacobbao/openbuddy-zephyr-7b-v14.1-code-orca-function-calling.

**Comment by homanp** [comment]
> > > > > Any update? I plan to test it out soon.
> > > 
> > > 
> > > > 
> > > 
> > > 
> > > > Working on it, hoping to release the coming week
> > > 
> > > 
> > > I trained a model based on mistral 7B with function calling data. I will test it when merged.
> > 
> > 
> > Anything you could share?
> 
> I uploaded to https://huggingface.co/jacobbao/openbuddy-zephyr-7b-v14.1-code-orca-function-calling.

@bdqfork would you be up for fine-tuning a function calling model for Superagent?

**Comment by bdqfork** [comment]
> would you be up for fine-tuning a function calling model for Superagent?

Yes, I can do it, but I only have one 2080ti, and training the 7b model with Qlora would take quite a long time.

**Comment by bdqfork** [comment]
> > > would you be up for fine-tuning a function calling model for Superagent?
> > 
> > 
> > Yes, I can do it, but I only have one 2080ti, and training the 7b model with Qlora would take quite a long time.
> 
> I can give you the GPUs. Would you be available for a call over zoom or Google meet to discuss?

I would be happy to, but my spoken English is not very good. Perhaps we can communicate through other means?

**Comment by homanp** [comment]
> > > > would you be up for fine-tuning a function calling model for Superagent?
> 
> > > 
> 
> > > 
> 
> > > Yes, I can do it, but I only have one 2080ti, and training the 7b model with Qlora would take quite a long time.
> 
> > 
> 
> > I can give you the GPUs. Would you be available for a call over zoom or Google meet to discuss?
> 
> 
> 
> I would be happy to, but my spoken English is not very good. Perhaps we can communicate through other means?

Sure, are you on our discord?

**Comment by bdqfork** [comment]
> > > > > would you be up for fine-tuning a function calling model for Superagent?
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > Yes, I can do it, but I only have one 2080ti, and training the 7b model with Qlora would take quite a long time.
> > 
> > 
> > > 
> > 
> > 
> > > I can give you the GPUs. Would you be available for a call over zoom or Google meet to discuss?
> > 
> > 
> > I would be happy to, but my spoken English is not very good. Perhaps we can communicate through other means?
> 
> Sure, are you on our discord?

yes

**Pull request closed without merging**
