### PR TITLE
Adding litellm for function calling

### LINKED ISSUE #595: Replace `LangchainAgent` with vanilla OpenAI function calling.
### ⚠️ Please check that this feature request hasn't been suggested before.

- [X] I searched previous [Ideas in Discussions](https://github.com/homanp/superagent/discussions/categories/ideas) didn't find any similar feature requests.
- [X] I searched previous [Issues](https://github.com/homanp/superagent/labels/enhancement) didn't find any similar feature requests.

### 🔖 Feature description

Since the LangchainAgent currently only runs OpenAI function calling we want to replace this with native OpenAI function calling using LiteLLM as documented here: https://docs.litellm.ai/docs/completion/function_call

We can keep Langchain implementations for tools, prompt etc. as is and only replace the completion. 

References: 

https://github.com/homanp/superagent/blob/main/libs/superagent/app/agents/langchain.py#L169

https://github.com/homanp/superagent/blob/main/libs/superagent/app/agents/langchain.py#L194

### 📝 Additional Context

_No response_

### Acknowledgements

- [X] My issue title is concise and descriptive.
- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for the maintainers to understand and evaluate this request.

### PR DESCRIPTION
**Pull request by elisalimli**
## Summary
This PR fixes #595 

- [ ] My code follows the code style of this project and passes `make format`.
- [ ] My change requires a change to the documentation.
- [ ] I have [updated the documentation](https://docs.superagent.sh/) accordingly.
- [ ] My change has adequate unit test coverage.

### CODE REVIEW

**Comment by shuriken-bytes** [comment]
- The `get_agent` method in the `base.py` file has been modified to include an `input` parameter.
- The `get_agent_litellm` method has been added to the `langchain.py` file.
- The `send_message` function in the `agents.py` file has been modified to use the `run` function returned by the `get_agent_litellm` method.

Overall, it seems like the changes are related to integrating the LLM (Language Learning Model) functionality into the agent. The `get_agent_litellm` method is responsible for setting up the LLM and handling tool calls, while the `send_message` function uses the LLM to send messages and retrieve responses.

It would be helpful to have more context on the purpose and requirements of the code to provide a more detailed review.

**Review by homanp — CHANGES_REQUESTED** [review]
please make sure Langfuse still works with this implementation. Please see the docs here: 

https://docs.litellm.ai/docs/observability/langfuse_integration

**Review by homanp — CHANGES_REQUESTED** [review]
Please remove code that is commented from this PR.

**Review by homanp — CHANGES_REQUESTED** [review]
@elisalimli please run `make format` and `make lint` to fix the formatting issues.

**Comment by elisalimli** [comment]
@homanp please review again.

**Comment by homanp** [comment]
> @homanp please review again.

The PR is still not passing the tests @elisalimli

**Pull request closed without merging**
