### PR TITLE
add error logging

### PR DESCRIPTION
**Pull request by dantheman0207**
## Summary

Added error logging to all the api calls. Just a quick pass through, happy to hear any feedback on any topic but especially format/style.

Fixes

Depends on

## Test plan

-

## Checklist

- [x] My code follows the code style of this project and passes `make format`.
- [ ] My change requires a change to the documentation.
- [ ] I have [updated the documentation](https://docs.superagent.sh/) accordingly.
- [ ] My change has adequate unit test coverage.

### CODE REVIEW

**Comment by dantheman0207** [comment]
Taking this out of draft as I'm happy to hear feedback but willing to make any changes you think best @homanp! I found this helpful and it also includes a few small improvements where the API would return HTTP 500 when prisma correctly returned an empty list for documents/agents etc that were not there.

**Comment by dantheman0207** [comment]
I can also separate the small bug fixes from the error logging if that's preferred.

**Comment by homanp** [comment]
@dantheman0207 looks great. Tell me when ready to merge

**Comment by dantheman0207** [comment]
I'm ready! Did some small manual testing for creating an agent and a tool and everything worked fine on my end!

**Review by homanp — APPROVED** [review]

**Comment by homanp** [comment]
> This is approved but not merged. Do you plan on merging, or waiting for a release or another PR @homanp ?
> 
> 
> 
> I'm not in a hurry.

Yep merging today

**Comment by homanp** [comment]
@dantheman0207 Did some small changes and merged!

**Pull request merged**
