### PR TITLE
More Tweaks

### PR DESCRIPTION
**Pull request by VictorHugoPilled**
## Summary

Caught some small errors in the docs and the UI.

Fixes

Majority of changes where things like: Id -> ID, Llm -> LLM, Api -> API and worflow -> workflow. 

- [x] My code follows the code style of this project and passes `make format`.
- [x] My change requires a change to the documentation.
- [x] I have [updated the documentation](https://docs.superagent.sh/) accordingly.
- [x] My change has adequate unit test coverage.

### CODE REVIEW

**Review by homanp — APPROVED** [review]
@VictorHugoPilled thanks a bunch!

**Review by homanp — CHANGES_REQUESTED** [review]
@VictorHugoPilled Could you please revert the openapi spec? It will get generated automatically depending on the API endpoints. Please revert to previous state.

**Comment by VictorHugoPilled** [comment]
Yes, my mistake, thought the openapi spec was only being used to create the docs.

**Review by homanp — APPROVED** [review]
Thanks again @VictorHugoPilled

**Comment by VictorHugoPilled** [comment]
No problem, I've learned so much throughout this process.

**Comment by homanp** [comment]
Closing in favour for #440

**Comment by homanp** [comment]
> No problem, I've learned so much throughout this process. 

Anything specific you are building?!

**Comment by VictorHugoPilled** [comment]
Right now I'm just trying to familiarize myself with the API. Further down the line, I'm planning on using Superagent to turn the system messages I've written for OpenAI's playground into Pydantic models. My ultimate goal is to be able to use these functions as a "dependency-light" way of incorporating multiple AI agents into automation workflows.

**Pull request closed without merging**
