### PR TITLE
Issue #210 Add chatgpt plugins

### PR DESCRIPTION
**Pull request by dantheman0207**
## Summary

This is an initial commit, I have not yet set it up and run it locally. Happy to get feedback!

Fixes

Depends on

## Test plan

Still setting up to run locally

-

## Checklist

- [ ] My code follows the code style of this project and passes `make format`.
- [ ] My change requires a change to the documentation.
- [ ] I have [updated the documentation](https://docs.superagent.sh/) accordingly.
- [ ] My change has adequate unit test coverage.

### CODE REVIEW

**Comment by homanp** [comment]
Are you running a virtualenv?

**Comment by dantheman0207** [comment]
> Are you running a virtualenv?

Yes I am, as set up by running the ./setup.sh script. Here's the output when I run it:

```
➜  superagent git:(enhancement-210-chatgpt_plugins) ./setup.sh 
created virtual environment CPython3.11.4.final.0-64 in 317ms
  creator CPython3Posix(dest=/Users/daniel/Projects/superagent/venv, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/Users/daniel/Library/Application Support/virtualenv)
    added seed packages: Deprecated==1.2.13, Jinja2==3.1.2, Markdown==3.4.3, MarkupSafe==2.1.2, Pillow==9.5.0, PyJWT==2.7.0, PyYAML==6.0, Pygments==2.15.1, SQLAlchemy==2.0.17, Wand==0.6.11, XlsxWriter==3.1.0, aiohttp==3.8.4, aiosignal==1.3.1, anyio==3.6.2, argilla==1.7.0, async_timeout==4.0.2, attrs==23.1.0, backoff==2.2.1, bcrypt==4.0.1, beautifulsoup4==4.12.2, black==23.3.0, bs4==0.0.1, cachetools==5.3.1, certifi==2023.5.7, cffi==1.15.1, charset_normalizer==3.1.0, click==8.1.3, cohere==4.5.1, commonmark==0.9.1, cryptography==40.0.2, dataclasses_json==0.5.8, dnspython==2.3.0, email_validator==2.0.0.post2, et_xmlfile==1.1.0, fastapi==0.95.1, filelock==3.12.1, flake8==6.0.0, frozenlist==1.3.3, fsspec==2023.6.0, google_api_core==2.11.1, google_auth==2.21.0, google_cloud_core==2.3.2, google_cloud_firestore==2.11.1, googleapis_common_protos==1.59.1, grpcio==1.56.0, grpcio_status==1.56.0, gunicorn==20.1.0, h11==0.14.0, httpcore==0.16.3, httptools==0.5.0, httpx==0.23.3, huggingface_hub==0.15.1, idna==3.4, itsdangerous==2.1.2, jaraco.context==4.3.0, joblib==1.2.0, langchain==0.0.218, langchainplus_sdk==0.0.17, llama_index==0.6.38.post1, loguru==0.7.0, lxml==4.9.2, marshmallow==3.19.0, marshmallow_enum==1.5.1, mccabe==0.7.0, monotonic==1.6, more_itertools==9.1.0, msg_parser==1.2.0, multidict==6.0.4, mypy_extensions==1.0.0, nltk==3.8.1, nodeenv==1.7.0, numexpr==2.8.4, numpy==1.23.5, olefile==0.46, openai==0.27.6, openapi_schema_pydantic==1.2.4, openpyxl==3.1.2, orjson==3.8.12, packaging==23.1, pandas==1.5.3, pathspec==0.11.1, pdfminer.six==20221105, pdfplumber==0.9.0, pinecone_client==2.2.1, pip==23.2, platformdirs==3.5.0, prisma==0.8.2, proto_plus==1.22.3, protobuf==4.23.3, psychicapi==0.8.0, pyasn1==0.5.0, pyasn1_modules==0.3.0, pycodestyle==2.10.0, pycparser==2.21, pydantic==1.10.7, pyflakes==3.0.1, pypandoc==1.11, pypdf==3.8.1, python_dateutil==2.8.2, python_decouple==3.8, python_docx==0.8.11, python_dotenv==1.0.0, python_magic==0.4.27, python_multipart==0.0.6, python_pptx==0.6.21, python_slugify==8.0.1, pytz==2023.3, regex==2023.5.5, replicate==0.8.3, requests==2.29.0, rfc3986==1.5.0, rich==13.0.1, rsa==4.9, ruff==0.0.265, safetensors==0.3.1, setuptools==68.0.0, six==1.16.0, sniffio==1.3.0, soupsieve==2.4.1, sse_starlette==1.5.0, starlette==0.26.1, superagent==0.0.1, superagent_py==0.0.29, tabulate==0.9.0, tenacity==8.2.2, text_unidecode==1.3, tiktoken==0.4.0, tokenizers==0.13.3, tomlkit==0.11.8, tqdm==4.65.0, transformers==4.30.2, typer==0.9.0, typing_extensions==4.5.0, typing_inspect==0.8.0, ujson==5.7.0, unstructured==0.6.5, urllib3==1.26.15, uuid==1.30, uvicorn==0.22.0, uvloop==0.17.0, watchfiles==0.19.0, websockets==11.0.3, wheel==0.40.0, wolframalpha==5.0.0, wrapt==1.14.1, xmltodict==0.13.0, yarl==1.9.2, youtube_transcript_api==0.6.1
  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
./setup.sh: line 8: poetry: command not found
./setup.sh: line 11: poetry: command not found
INFO:     Will watch for changes in these directories: ['/Users/daniel/Projects/superagent']
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [8893] using WatchFiles
Process SpawnProcess-1:
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/daniel/Projects/superagent/venv/lib/python3.11/site-packages/uvicorn/_subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/Users/daniel/Projects/superagent/venv/lib/python3.11/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/Users/daniel/Projects/superagent/venv/lib/python3.11/site-packages/uvicorn/server.py", line 68, in serve
    config.load()
  File "/Users/daniel/Projects/superagent/venv/lib/python3.11/site-packages/uvicorn/config.py", line 473, in load
    self.loaded_app = import_from_string(self.app)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/daniel/Projects/superagent/venv/lib/python3.11/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/daniel/Projects/superagent/app/main.py", line 6, in <module>
    from app.lib.prisma import prisma
  File "/Users/daniel/Projects/superagent/app/lib/prisma.py", line 1, in <module>
    from prisma import Prisma
  File "<frozen importlib._bootstrap>", line 1229, in _handle_fromlist
  File "/Users/daniel/Projects/superagent/venv/lib/python3.11/site-packages/prisma/__init__.py", line 43, in __getattr__
    raise RuntimeError(
RuntimeError: The Client hasn't been generated yet, you must run `prisma generate` before you can use the client.
See https://prisma-client-py.readthedocs.io/en/stable/reference/troubleshooting/#client-has-not-been-generated-yet
```

**Comment by homanp** [comment]
> > Are you running a virtualenv?
> 
> 
> 
> Yes I am, as set up by running the ./setup.sh script. Here's the output when I run it:
> 
> 
> 
> ```
> 
> ➜  superagent git:(enhancement-210-chatgpt_plugins) ./setup.sh 
> 
> created virtual environment CPython3.11.4.final.0-64 in 317ms
> 
>   creator CPython3Posix(dest=/Users/daniel/Projects/superagent/venv, clear=False, no_vcs_ignore=False, global=False)
> 
>   seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/Users/daniel/Library/Application Support/virtualenv)
> 
>     added seed packages: Deprecated==1.2.13, Jinja2==3.1.2, Markdown==3.4.3, MarkupSafe==2.1.2, Pillow==9.5.0, PyJWT==2.7.0, PyYAML==6.0, Pygments==2.15.1, SQLAlchemy==2.0.17, Wand==0.6.11, XlsxWriter==3.1.0, aiohttp==3.8.4, aiosignal==1.3.1, anyio==3.6.2, argilla==1.7.0, async_timeout==4.0.2, attrs==23.1.0, backoff==2.2.1, bcrypt==4.0.1, beautifulsoup4==4.12.2, black==23.3.0, bs4==0.0.1, cachetools==5.3.1, certifi==2023.5.7, cffi==1.15.1, charset_normalizer==3.1.0, click==8.1.3, cohere==4.5.1, commonmark==0.9.1, cryptography==40.0.2, dataclasses_json==0.5.8, dnspython==2.3.0, email_validator==2.0.0.post2, et_xmlfile==1.1.0, fastapi==0.95.1, filelock==3.12.1, flake8==6.0.0, frozenlist==1.3.3, fsspec==2023.6.0, google_api_core==2.11.1, google_auth==2.21.0, google_cloud_core==2.3.2, google_cloud_firestore==2.11.1, googleapis_common_protos==1.59.1, grpcio==1.56.0, grpcio_status==1.56.0, gunicorn==20.1.0, h11==0.14.0, httpcore==0.16.3, httptools==0.5.0, httpx==0.23.3, huggingface_hub==0.15.1, idna==3.4, itsdangerous==2.1.2, jaraco.context==4.3.0, joblib==1.2.0, langchain==0.0.218, langchainplus_sdk==0.0.17, llama_index==0.6.38.post1, loguru==0.7.0, lxml==4.9.2, marshmallow==3.19.0, marshmallow_enum==1.5.1, mccabe==0.7.0, monotonic==1.6, more_itertools==9.1.0, msg_parser==1.2.0, multidict==6.0.4, mypy_extensions==1.0.0, nltk==3.8.1, nodeenv==1.7.0, numexpr==2.8.4, numpy==1.23.5, olefile==0.46, openai==0.27.6, openapi_schema_pydantic==1.2.4, openpyxl==3.1.2, orjson==3.8.12, packaging==23.1, pandas==1.5.3, pathspec==0.11.1, pdfminer.six==20221105, pdfplumber==0.9.0, pinecone_client==2.2.1, pip==23.2, platformdirs==3.5.0, prisma==0.8.2, proto_plus==1.22.3, protobuf==4.23.3, psychicapi==0.8.0, pyasn1==0.5.0, pyasn1_modules==0.3.0, pycodestyle==2.10.0, pycparser==2.21, pydantic==1.10.7, pyflakes==3.0.1, pypandoc==1.11, pypdf==3.8.1, python_dateutil==2.8.2, python_decouple==3.8, python_docx==0.8.11, python_dotenv==1.0.0, python_magic==0.4.27, python_multipart==0.0.6, python_pptx==0.6.21, python_slugify==8.0.1, pytz==2023.3, regex==2023.5.5, replicate==0.8.3, requests==2.29.0, rfc3986==1.5.0, rich==13.0.1, rsa==4.9, ruff==0.0.265, safetensors==0.3.1, setuptools==68.0.0, six==1.16.0, sniffio==1.3.0, soupsieve==2.4.1, sse_starlette==1.5.0, starlette==0.26.1, superagent==0.0.1, superagent_py==0.0.29, tabulate==0.9.0, tenacity==8.2.2, text_unidecode==1.3, tiktoken==0.4.0, tokenizers==0.13.3, tomlkit==0.11.8, tqdm==4.65.0, transformers==4.30.2, typer==0.9.0, typing_extensions==4.5.0, typing_inspect==0.8.0, ujson==5.7.0, unstructured==0.6.5, urllib3==1.26.15, uuid==1.30, uvicorn==0.22.0, uvloop==0.17.0, watchfiles==0.19.0, websockets==11.0.3, wheel==0.40.0, wolframalpha==5.0.0, wrapt==1.14.1, xmltodict==0.13.0, yarl==1.9.2, youtube_transcript_api==0.6.1
> 
>   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
> 
> ./setup.sh: line 8: poetry: command not found
> 
> ./setup.sh: line 11: poetry: command not found
> 
> INFO:     Will watch for changes in these directories: ['/Users/daniel/Projects/superagent']
> 
> INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
> 
> INFO:     Started reloader process [8893] using WatchFiles
> 
> Process SpawnProcess-1:
> 
> Traceback (most recent call last):
> 
>   File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
> 
>     self.run()
> 
>   File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/process.py", line 108, in run
> 
>     self._target(*self._args, **self._kwargs)
> 
>   File "/Users/daniel/Projects/superagent/venv/lib/python3.11/site-packages/uvicorn/_subprocess.py", line 76, in subprocess_started
> 
>     target(sockets=sockets)
> 
>   File "/Users/daniel/Projects/superagent/venv/lib/python3.11/site-packages/uvicorn/server.py", line 61, in run
> 
>     return asyncio.run(self.serve(sockets=sockets))
> 
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 190, in run
> 
>     return runner.run(main)
> 
>            ^^^^^^^^^^^^^^^^
> 
>   File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 118, in run
> 
>     return self._loop.run_until_complete(task)
> 
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
> 
>   File "/Users/daniel/Projects/superagent/venv/lib/python3.11/site-packages/uvicorn/server.py", line 68, in serve
> 
>     config.load()
> 
>   File "/Users/daniel/Projects/superagent/venv/lib/python3.11/site-packages/uvicorn/config.py", line 473, in load
> 
>     self.loaded_app = import_from_string(self.app)
> 
>                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "/Users/daniel/Projects/superagent/venv/lib/python3.11/site-packages/uvicorn/importer.py", line 21, in import_from_string
> 
>     module = importlib.import_module(module_str)
> 
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py", line 126, in import_module
> 
>     return _bootstrap._gcd_import(name[level:], package, level)
> 
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
> 
>   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
> 
>   File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
> 
>   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
> 
>   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
> 
>   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
> 
>   File "/Users/daniel/Projects/superagent/app/main.py", line 6, in <module>
> 
>     from app.lib.prisma import prisma
> 
>   File "/Users/daniel/Projects/superagent/app/lib/prisma.py", line 1, in <module>
> 
>     from prisma import Prisma
> 
>   File "<frozen importlib._bootstrap>", line 1229, in _handle_fromlist
> 
>   File "/Users/daniel/Projects/superagent/venv/lib/python3.11/site-packages/prisma/__init__.py", line 43, in __getattr__
> 
>     raise RuntimeError(
> 
> RuntimeError: The Client hasn't been generated yet, you must run `prisma generate` before you can use the client.
> 
> See https://prisma-client-py.readthedocs.io/en/stable/reference/troubleshooting/#client-has-not-been-generated-yet
> 
> ```

Run `prisma generate`

**Comment by homanp** [comment]
@dantheman0207 ping when you want me to review this!

**Comment by dantheman0207** [comment]
I merged in the changes from [this (approved but not yet merged) PR](https://github.com/homanp/superagent/pull/215) as I needed more error logging to debug issues with tools and agents. Otherwise the changes were not that big. I'm terrible with React, but one possibility I would like to explore on the frontend is automatically filling in the description by pulling it from the link to the ChatGPT plugin manifest. [Here's a link to an example](https://labs.cactiml.com/.well-known/ai-plugin.json), you can see it includes both a human and AI friendly description.

**Comment by homanp** [comment]
> I merged in the changes from [this (approved but not yet merged) PR](https://github.com/homanp/superagent/pull/215) as I needed more error logging to debug issues with tools and agents. Otherwise the changes were not that big. I'm terrible with React, but one possibility I would like to explore on the frontend is automatically filling in the description by pulling it from the link to the ChatGPT plugin manifest. [Here's a link to an example](https://labs.cactiml.com/.well-known/ai-plugin.json), you can see it includes both a human and AI friendly description.

Hey @dantheman0207 would you mind merging in main into this? After that I'll review/test/merge.

**Comment by dantheman0207** [comment]
@homanp Done! Definitely simplifies the review :)

**Comment by dantheman0207** [comment]
Just pushed another fix which added a single empty line to fix the formatting to comply with lint. My bad.

**Comment by homanp** [comment]
> Just pushed another fix which added a single empty line to fix the formatting to comply with lint. My bad.

Cool, I'll have to merge an other PR in order to merge this. Do tomorrow some time.

**Comment by dantheman0207** [comment]
For testing plugins:
1. MedQA: Here's the URL for the plugin: `https://labs.cactiml.com/.well-known/ai-plugin.json`. Here's an example query: `What are the symptoms of rhabdomyolysis?`. That should trigger the plugin, you'll be able to see it's triggered in the logs.
2. Pulsetic: Here's the URL for the plugin: `https://api.pulsetic.com/.well-known/ai-plugin.json`. Here's an example query: `Is google.com up right now?`. That should trigger the plugin.
3. Youtube plugin: Here's the URL for the plugin: `https://vcaption.maila.ai/.well-known/ai-plugin.json`. Here's an example query: `Why does Andrej think you should work on AI agents in this video: https://www.youtube.com/watch?v=fqVLjtvWgq8 `

Here's the backend output from running the 3rd example:
```
> Entering new  chain...

Invoking: `VideoCaptions` with `{'tool_input': 'https://www.youtube.com/watch?v=fqVLjtvWgq8'}`
responded: {content}

Usage Guide: Converts YouTube video into Text. If totalSegments are more than 1, transcribe each portion of the video separately until the full video is transcribed.

OpenAPI Spec: {'openapi': '3.1.0', 'info': {'title': 'Video Transcription API', 'version': '1.0.0'}, 'servers': [{'url': 'https://vcaption.maila.ai'}], 'paths': {'/api/transcription': {'post': {'summary': 'Transcribe a section of a video', 'operationId': 'transcribeVideo', 'requestBody': {'required': True, 'content': {'application/json': {'schema': {'type': 'object', 'properties': {'videoId': {'type': 'string', 'description': 'YouTube video ID to be transcribed'}, 'segment': {'type': 'integer', 'description': 'Segment number to transcribe, with each segment holding a maximum of 2k words.'}, 'includeTimestamp': {'type': 'boolean', 'description': 'Specifies whether to include timestamps in the transcription'}}}}}}, 'responses': {'200': {'description': 'A successful response', 'content': {'application/json': {'schema': {'type': 'object', 'properties': {'totalSegments': {'type': 'integer', 'description': 'Total number of segments in the video'}, 'currentSegment': {'type': 'integer', 'description': 'The current transcribed segment number'}, 'transcribedText': {'type': 'string', 'description': 'The transcribed text of the current segment'}, 'error': {'type': 'string', 'description': 'Error message, if any'}}}}}}, '400': {'description': 'Bad request, no transcription available', 'content': {'application/json': {'schema': {'type': 'object', 'properties': {'error': {'type': 'string', 'description': 'Error message'}}}}}}}}}}}
Invoking: `requests_post` with `{"url": "https://vcaption.maila.ai/api/transcription", "data": {"videoId": "fqVLjtvWgq8", "segment": 1, "includeTimestamp": false}}`


{"totalSegments":1,"currentSegment":1,"transcribedText":"information from hundred and secretary okay hi everyone the microphone is working right I think yes so I was recruited uh to say some words of inspiration on the topic of AI agents um so I actually wanted to begin with a story I think like AI agents are near and dear to my heart to some extent because this is a story drawing very early open AI back when it was like maybe a dozen people and this was 2016 or so and the Zeitgeist of the day actually were RL agents and so everyone's really interested in building agents but very much at the time it was in the context of the games primarily so it was the height of excitement around Atari and all the game playing and so on and so my project at openai was trying to focus the roh notes not on things I want to Zuma's Revenge and so on but on uh you know using computers using keyboard and mouse and so I wanted to make it useful I wanted to make them do a lot of tasks and this project was called world of bits and I I worked on it together with Tennessee and Jim fans there's someone here and so the three of us ended up publishing a paper it's not a super amazing paper because basically at the time all you had was a hammer was uh three percent learning and so we have these very simple web pages that we're trying to like order order a flight or order some something to eat and very simple web pages and we were mashing buttons and mouse clicks and so on and we were trying to like stumble our way into the higher Awards and obviously it didn't work so the technology was just not ready and that was not the right thing to work on at the time and so it turns out that the right thing to do at the time was actually to forget about AI agents altogether and start building language models and then language models now we're back here five years later I got distracted with self-driving for a bit there [Music] [Laughter] and so the way you would approach these problems today is completely different in fact all of you are working on AI agents but you're not using any reinforcement learning probably and so that's so crazy and I don't think we would have anticipated it at the time uh it's just the way this played out it's very it's very interesting so I want to spend a bit of time on like okay what is causing all this hype I think obviously all the reason that all of you are interested in this topic is that I think it's very obvious to a lot of people that AGI will take the form factor of some kind of an AI agent and it's not just going to be a single agent thing there's going to be many agents maybe they're going to be in organizations or civilizations of digital entities and I think it's just extremely inspiring to sort of like think through it's kind of crazy I also want to pour some water on this too though I think there is a large class of problems that I think are very easy to imagine they're very easy to build demos for are actually extremely hard to make products out of and I think many things fall into this category I would tell self-driving is an example of it actually self-driving is very easy to imagine very easy to build a demo of a car driving around the block but making it into a product takes a decade and the same is true I think for for example VR we're used to imaginable demos but uh getting a tour again it takes a decade and I think agents are kind of like that as well very easy to imagine excited to get excited about build demos off but I think if you're in it you should be in it for a decade and actually make it work um one other thing I want to say is that I think it's kind of interesting to go back to Neuroscience now and take inspiration from it again in some ways I think this was true in the early days of deep learning but it's now true also again for United so it's been kind of interesting for me to think about uh sort of all the equivalents so in particular I think a lot of us when we're um it's clear that language models are part of a solution but you know how do you build an entire digital entity that has all the cognitive tools that humans have so obviously we all think we need some kind of a potentially system to uh to actually like plan ahead and think through and reflect on what we're doing and there's a lot more that you can take inspiration from so for example the hippocampus is important what is the importance of the hippocampus for AI agents well well it's uh somehow like recording uh memory traces and maybe indexing them using embeddinance and retrieving from them uh something like that so maybe that's kind of like the retrieval kind of thing in the brain we I think understand how to build visual auditory cortex roughly but there's many still things that like what are The Columns of them in AI agents what is the uh we are doing what does it look like in an AI agent what does the balance doing the sort of integrates all this information together it's kind of like potentially the seat of Consciousness and it's got this very interesting neural circuit where if you think of your brain as sort of like multiple entities fighting for the microphone as to like what you're going to do the following this is probably where that happens it's kind of interesting so I actually brought a book that I like the girl says it's called bringing Behavior by David Eagleman and I found this very interesting and inspirational so I leave it here if you'd like to I'll go through it and paste through it and I just think that there's some interesting inspiration to again draw from neuroscience and just like we did early on in with respect to how we design an individual neuron we can do that again today me um finally I wanted to end with some words of inspiration uh what's interesting and not obvious is that you guys building AI agents are actually at the Forefront of capability of the aisle today um and all the big Labs like llm labs and so on I suspect are not at the edge of the case but look you are at the first benefit uh so opening up for example is very good at training Master Transformer related models so as an example one way to put it is if the paper comes out it proposes some different way of training and Transformer the internal sprocket open AI is something along the rise of oh yeah someone tried that two and a half years ago and here's what happened and here's why it didn't work and it's very well understood and very um very well mapped out but when a new agent paper comes out we're all interested in when we look at it and we're like oh that's really cool that's another one and that's because uh you know a team didn't have like five years to spend on it and it's competing now with all of you and the entrepreneurs and actors and so on it's really hard to do so yeah I think it's really inspiring that you are at the edge of capability and uh on something that is obviously very important in transformational and so with those words I think uh it's great to see what you guys don't [Applause]"}Andrej Karpathy believes that working on AI agents is important because he sees them as the form factor of AGI (Artificial General Intelligence). He envisions not just a single AI agent, but many agents possibly forming organizations or civilizations of digital entities. 

However, he also cautions that while it's easy to imagine and build demos for AI agents, turning them into products is a long-term commitment that could take a decade. He likens this to the development of self-driving cars and VR, which are easy to demo but take a long time to productize.

He also suggests looking to neuroscience for inspiration in building AI agents, drawing parallels between various parts of the brain and potential components of an AI agent. For example, he mentions the hippocampus's role in recording and retrieving memory traces, which could be similar to retrieval mechanisms in AI agents.

Finally, he finds it inspiring that those working on AI agents are at the forefront of AI capabilities, even ahead of big labs. He encourages continued exploration and innovation in this field, emphasizing its transformative potential.

> Finished chain.
```

**Comment by homanp** [comment]
@dantheman0207 I will be merging this together with #223

**Pull request closed without merging**
