### PR TITLE
Update schema.prisma

### PR DESCRIPTION
**Pull request by brappier**
## Summary

Fixes

Depends on

## Test plan
Yes

## Screenshots

image

## Checklist
- did some pull request

### CODE REVIEW

**Comment by brappier** [comment]
Hey @homanp  please accept my pull. i am a CS graduate with 4 years of expereince in my college learning about computer and stuff. i have worked with MS word as well. I have done html and UI too . 
I have been told to do github contributions and doing pulls , i even say tutisals on how to do it. 

please merge it , and give me feedback. I am a coder who wants job

**Comment by brappier** [comment]
@homanp  ??????? @possibilities @heresandyboy @mrahmadt @dantheman0207 @geohot

**Comment by homanp** [comment]
You have removed the DB schema, why would we want to merge that?

**Comment by homanp** [comment]
> FYI its a joke.

kind of figured!

**Pull request closed without merging**
