### PR TITLE
Support for data analysis with E2B

### PR DESCRIPTION
**Pull request by mlejva**
## Summary

This PR adds support for code execution with data analysis (and charts specifically) using E2B. 

There's a few things that I'm not sure how exactly you'd like to handle @homanp so I left comments in the code. I can either leave it up to you or help you with any further implementation. Specifically it's about:
- Streaming stdout, stderr, and artifacts as the code is being executed so users can get fast visual response
- The artifacts (those are the charts that code generates when the `show()` function is called with `matplotlib`) needs to be displayed to a user. I prepared the `_download_artifact()` function for this.
- E2B sandbox is now represented through a long running session and variable called `_session`. This means the E2B session is running for the whole lifecycle of an agent. At some point after an agent is done, you really should call `_session.close()`. I prepared the `_close_session()` for this.

It's also possible for users to upload their files (eg CSV data files) to the running E2B session. I didn't implement this functionality in this PR since it requires UI changes. You can just use `remote_filepath = session.upload_file()` and you're good to though.
One of the use-cases is to upload the file and then tell LLM about the file in a prompt like this for example:
```python
f"User has uploaded the {remote_filepath} and has following questions about it: ..."
```

Let me know if you have any other questions. Always happy to help.

## Checklist

- [x] My code follows the code style of this project and passes `make format`.
- [ ] My change requires a change to the documentation.
- [ ] I have [updated the documentation](https://docs.superagent.sh/) accordingly.
- [ ] My change has adequate unit test coverage.

### CODE REVIEW

**Review by homanp — APPROVED** [review]
Thank u @mlejva 🙏

**Comment by homanp** [comment]
@mlejva How do I pass generated images etc. to UI? Is the image present in `stdout`?

**Comment by mlejva** [comment]
> @mlejva How do I pass generated images etc. to UI? Is the image present in `stdout` or do I need to return the `_download_artifacts`?

Hey @homanp, `artifacts` are made for this. Each `artifact` is basically a chart file created by `matplotlib` (in 99%, the LLM will use matplotlib, let us know if you need support for additional plotting libraries). You can then call `artifact.download()` and it returns the chart represented in bytes. You can then send it to frontend, save it to a DB, etc.

I created a function for this in this PR
```python
  def _download_artifact(self, artifact):
        # Artifact is a chart file created by matplotlib
        # You can download it right from the E2B LLM Sandbox
        #
        # `artifact_bytes` is a chart file (.png) in bytes
        # TODO: Send the artifact bytes to frontend, save it to DB, etc
        artifact_bytes = artifact.download()
```

**Comment by homanp** [comment]
> > @mlejva How do I pass generated images etc. to UI? Is the image present in `stdout` or do I need to return the `_download_artifacts`?
> 
> Hey @homanp, `artifacts` are made for this. Each `artifact` is basically a chart file created by `matplotlib` (in 99%, the LLM will use matplotlib, let us know if you need support for additional plotting libraries). You can then call `artifact.download()` and it returns the chart represented in bytes. You can then send it to frontend, save it to a DB, etc.
> 
> I created a function for artifacts in this PR [here](https://github.com/homanp/superagent/blob/main/libs/superagent/app/tools/e2b.py#L22)
> 
> ```python
>   def _download_artifact(self, artifact):
>         # Artifact is a chart file created by matplotlib
>         # You can download it right from the E2B LLM Sandbox
>         #
>         # `artifact_bytes` is a chart file (.png) in bytes
>         # TODO: Send the artifact bytes to frontend, save it to DB, etc
>         artifact_bytes = artifact.download()
> ```

Got it. What would you say would be best practice? Downloading/saving then returning the saved file/url together with stdout?

**Comment by mlejva** [comment]
> Downloading/saving then returning the saved file/url together with stdout?

Yeah. You can wait for the whole code to finish running and then grab [stdout, stderr, and artifacts](https://github.com/homanp/superagent/blob/main/libs/superagent/app/tools/e2b.py#L32) and send it to the frontend.
Optionally, you could call `artifact.download()` as soon as you get it by listening to the `on_artifact` [here](https://github.com/homanp/superagent/blob/main/libs/superagent/app/tools/e2b.py#L37).


One thing to watch out for is that the representation of the image is correct on the frontend. I'm not sure how conversion from the Python `bytes` to JS `ArrayBuffer` or `Uint8Array` looks like from the top of my head. I'll do a bit of research on it and ideally provide  you with a snippet.

I think you want to send image in bytes to frontend (as byte array in base64) together with stdout/stderr. Then on the frontend, you can display the image directly with something like [this](https://stackoverflow.com/questions/9463981/displaying-a-byte-array-as-an-image-using-javascript).

**Comment by mlejva** [comment]
thinking about it - another nice option might be steaming the stdout, stderr, and artifacts right away to Supabase and then use their realtime functionality and listen to the DB changes on frontend.

**Comment by mlejva** [comment]
I did a bit of research on how to send the image bytes from Python to JavaScript frontend. You can convert `bytes` to base64 string and send it to the frontend from server. Like this:
```python
import base64

stdout, stderr, artifacts = session.run_python(llm_code)
for artifact in artifacts:
    artifact_bytes = artifact.download()
    base64_content = base64.b64encode(artifact_bytes).decode("utf-8")
   # TODO: Send `base64_content` back to frontend
```

Then on the frontend you can pass the base64 string you created directly to the image's `src` field like this:
```jsx
<Img src={`data:image/png;base64,${base64String}`} alt="Base64 Encoded Image" />
```

**Pull request merged**
