### PR TITLE
Add Ability for different text splitters

### PR DESCRIPTION
**Pull request by yusofy**
Added ability to have different types of text splitters. 
Added the following:
- CharacterTextSplitter
- RecursiveCharacterTextSplitter
- tiktoken splitter
- spaCy
- NLTK
- Hugging Face Tokenizer

By Default, the CharacterTextSplitter, is utilized to keep backwards compatibility

### CODE REVIEW

**Comment by yusofy** [comment]
@homanp I am having an issue with trying to pass text splitter variable via the API. The prisma.document.create is throwing an error. I will admit I am lost why it is not working, if you don't mind taking a look. I have a feeling it's something simple I'm missing.

**Comment by homanp** [comment]
> @homanp I am having an issue with trying to pass text splitter variable via the API. The prisma.document.create is throwing an error. I will admit I am lost why it is not working, if you don't mind taking a look. I have a feeling it's something simple I'm missing. 

Hey! Will take a look in a couple of hours!

**Comment by homanp** [comment]
@yusofy There is an issue with URL document loader somewhere. It was introduced by the refactoring I merged yesterday. Need to dig into that and fix.

**Comment by homanp** [comment]
@yusofy I've resolved the issue, could you please test this out.

**Comment by yusofy** [comment]
Hey @homanp  now with or without splitter, I'm getting the error I was getting last night. Here is the stack trace:

`ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/mnt/d/code/superagent/./app/api/documents.py", line 19, in create_document
    document = prisma.document.create(
  File "/home/user/.local/lib/python3.10/site-packages/prisma/actions.py", line 2227, in create
    resp = self._client._execute(
  File "/home/user/.local/lib/python3.10/site-packages/prisma/client.py", line 427, in _execute
    return self._engine.query(builder.build(), tx_id=self._tx_id)
  File "/home/user/.local/lib/python3.10/site-packages/prisma/engine/query.py", line 226, in query
    return self.request(
  File "/home/user/.local/lib/python3.10/site-packages/prisma/engine/http.py", line 123, in request
    return utils.handle_response_errors(resp, errors_data)
  File "/home/user/.local/lib/python3.10/site-packages/prisma/engine/utils.py", line 180, in handle_response_errors
    raise prisma_errors.MissingRequiredValueError(error)
prisma.errors.MissingRequiredValueError: Unable to match input value to any allowed input type for the field. Parse errors: [`data.user`: A value is required but not set, `createOneDocument.data.splitter`: Field does not exist in enclosing type.]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/.local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/home/user/.local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/home/user/.local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/home/user/.local/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/home/user/.local/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/home/user/.local/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/home/user/.local/lib/python3.10/site-packages/fastapi/routing.py", line 241, in app
    raw_response = await run_endpoint_function(
  File "/home/user/.local/lib/python3.10/site-packages/fastapi/routing.py", line 167, in run_endpoint_function
    return await dependant.call(**values)
  File "/mnt/d/code/superagent/./app/api/documents.py", line 43, in create_document
    raise HTTPException(
fastapi.exceptions.HTTPException

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/uvicorn/protocols/http/h11_impl.py", line 373, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/lib/python3/dist-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/home/user/.local/lib/python3.10/site-packages/fastapi/applications.py", line 282, in __call__
    await super().__call__(scope, receive, send)
  File "/home/user/.local/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/user/.local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/user/.local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/user/.local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "/home/user/.local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 88, in __call__
    response = await handler(request, exc)
  File "/home/user/.local/lib/python3.10/site-packages/fastapi/exception_handlers.py", line 15, in http_exception_handler
    return JSONResponse(
  File "/home/user/.local/lib/python3.10/site-packages/starlette/responses.py", line 196, in __init__
    super().__init__(content, status_code, headers, media_type, background)
  File "/home/user/.local/lib/python3.10/site-packages/starlette/responses.py", line 55, in __init__
    self.body = self.render(content)
  File "/home/user/.local/lib/python3.10/site-packages/starlette/responses.py", line 199, in render
    return json.dumps(
  File "/usr/lib/python3.10/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type MissingRequiredValueError is not JSON serializable`

**Comment by homanp** [comment]
> Hey @homanp  now with or without splitter, I'm getting the error I was getting last night. Here is the stack trace:
> 
> 
> 
> ```
> 
> ERROR:    Exception in ASGI application
> 
> Traceback (most recent call last):
> 
>   File "/mnt/d/code/superagent/./app/api/documents.py", line 19, in create_document
> 
>     document = prisma.document.create(
> 
>   File "/home/user/.local/lib/python3.10/site-packages/prisma/actions.py", line 2227, in create
> 
>     resp = self._client._execute(
> 
>   File "/home/user/.local/lib/python3.10/site-packages/prisma/client.py", line 427, in _execute
> 
>     return self._engine.query(builder.build(), tx_id=self._tx_id)
> 
>   File "/home/user/.local/lib/python3.10/site-packages/prisma/engine/query.py", line 226, in query
> 
>     return self.request(
> 
>   File "/home/user/.local/lib/python3.10/site-packages/prisma/engine/http.py", line 123, in request
> 
>     return utils.handle_response_errors(resp, errors_data)
> 
>   File "/home/user/.local/lib/python3.10/site-packages/prisma/engine/utils.py", line 180, in handle_response_errors
> 
>     raise prisma_errors.MissingRequiredValueError(error)
> 
> prisma.errors.MissingRequiredValueError: Unable to match input value to any allowed input type for the field.
> 
> Parse errors: [`data.user\`: A value is required but not set, \`createOneDocument.data.splitter\`: 
> 
> Field does not exist in enclosing type.]
> 
> 
> 
> During handling of the above exception, another exception occurred:
> 
> 
> 
> Traceback (most recent call last):
> 
>   File "/home/user/.local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
> 
>     await self.app(scope, receive, sender)
> 
>   File "/home/user/.local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
> 
>     raise e
> 
>   File "/home/user/.local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
> 
>     await self.app(scope, receive, send)
> 
>   File "/home/user/.local/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
> 
>     await route.handle(scope, receive, send)
> 
>   File "/home/user/.local/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
> 
>     await self.app(scope, receive, send)
> 
>   File "/home/user/.local/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
> 
>     response = await func(request)
> 
>   File "/home/user/.local/lib/python3.10/site-packages/fastapi/routing.py", line 241, in app
> 
>     raw_response = await run_endpoint_function(
> 
>   File "/home/user/.local/lib/python3.10/site-packages/fastapi/routing.py", line 167, in run_endpoint_function
> 
>     return await dependant.call(**values)
> 
>   File "/mnt/d/code/superagent/./app/api/documents.py", line 43, in create_document
> 
>     raise HTTPException(
> 
> fastapi.exceptions.HTTPException
> 
> 
> 
> During handling of the above exception, another exception occurred:
> 
> 
> 
> Traceback (most recent call last):
> 
>   File "/usr/lib/python3/dist-packages/uvicorn/protocols/http/h11_impl.py", line 373, in run_asgi
> 
>     result = await app(self.scope, self.receive, self.send)
> 
>   File "/usr/lib/python3/dist-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
> 
>     return await self.app(scope, receive, send)
> 
>   File "/home/user/.local/lib/python3.10/site-packages/fastapi/applications.py", line 282, in __call__
> 
>     await super().__call__(scope, receive, send)
> 
>   File "/home/user/.local/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
> 
>     await self.middleware_stack(scope, receive, send)
> 
>   File "/home/user/.local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
> 
>     raise exc
> 
>   File "/home/user/.local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
> 
>     await self.app(scope, receive, _send)
> 
>   File "/home/user/.local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 83, in __call__
> 
>     await self.app(scope, receive, send)
> 
>   File "/home/user/.local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 88, in __call__
> 
>     response = await handler(request, exc)
> 
>   File "/home/user/.local/lib/python3.10/site-packages/fastapi/exception_handlers.py", line 15, in http_exception_handler
> 
>     return JSONResponse(
> 
>   File "/home/user/.local/lib/python3.10/site-packages/starlette/responses.py", line 196, in __init__
> 
>     super().__init__(content, status_code, headers, media_type, background)
> 
>   File "/home/user/.local/lib/python3.10/site-packages/starlette/responses.py", line 55, in __init__
> 
>     self.body = self.render(content)
> 
>   File "/home/user/.local/lib/python3.10/site-packages/starlette/responses.py", line 199, in render
> 
>     return json.dumps(
> 
>   File "/usr/lib/python3.10/json/__init__.py", line 238, in dumps
> 
>     **kw).encode(obj)
> 
>   File "/usr/lib/python3.10/json/encoder.py", line 199, in encode
> 
>     chunks = self.iterencode(o, _one_shot=True)
> 
>   File "/usr/lib/python3.10/json/encoder.py", line 257, in iterencode
> 
>     return _iterencode(o, 0)
> 
>   File "/usr/lib/python3.10/json/encoder.py", line 179, in default
> 
>     raise TypeError(f'Object of type {o.__class__.__name__} '
> 
> TypeError: Object of type MissingRequiredValueError is not JSON serializable
> 
> ```

This seems like a migration issue. Try running them and recreate your Prisma client.

This works for me with the following payload:

```
{
  "name".
  "type",
  "authorization": null,
  "splitter": null,
}
```

**Comment by yusofy** [comment]
@homanp you were right. it was prisma migration related. I ended up removing the prisma packages (I had both node and python) and now it's working with splitter and without. Also choosing the type is working! 
So we're good to merge if you're good with that!

**Comment by homanp** [comment]
> @homanp you were right. it was prisma migration related. I ended up removing the prisma packages (I had both node and python) and now it's working with splitter and without. Also choosing the type is working! 
> 
> So we're good to merge if you're good with that!

Less go 🔥

**Comment by homanp** [comment]
Big thanks for this! One other thing I think we should do is always have a look at how embeddings are being created. Doesn't make sense to create them for each query, we could perhaps just save them.

**Pull request merged**
